# This is a list of dictionry.  Key is the node, value is the full file path
submissionfiles:
  - diagnosis: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Insilicom\phs000720-20250509T183542Z-1-001\phs000720\Clean_loading\final_df_diagnosis.csv'
  - file: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Insilicom\phs000720-20250509T183542Z-1-001\phs000720\Clean_loading\final_df_file.csv'
  - genomic_info: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Insilicom\phs000720-20250509T183542Z-1-001\phs000720\Clean_loading\final_df_genomic_info.csv'
  - participant: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Insilicom\phs000720-20250509T183542Z-1-001\phs000720\Clean_loading\final_df_participant.csv'
  - sample: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Insilicom\phs000720-20250509T183542Z-1-001\phs000720\Clean_loading\final_df_sample.csv'
  - study: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Insilicom\phs000720-20250509T183542Z-1-001\phs000720\Clean_loading\final_df_study.csv'
modelfiles:
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/6.0.4/model-desc/cds-model.yml"
  - "https://raw.githubusercontent.com/CBIIT/cds-model/refs/heads/6.0.4/model-desc/cds-model-props.yml"
outputdir: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\TDP Fixes\Insilicom\phs000720\'
fixes:
  fileid: 
    file: 'file_id'
  participantphs:
    participant: 'study.phs_accession'
    study: 'phs_accession'
  study_participant_id:
    participant: 'study_participant_id'
  diagnosis_id:
    idfield: 'diagnosis_id'
    diagnosis: 'primary_diagnosis'
    site: 'primary_site'
  study_diagnosis_id:
    idfield: 'study_diagnosis_id'
    diagnosis: 'diagnosis_id'
    participant: 'participant.study_participant_id'
  genomic_info_id:
    node: 'genomic_info'
    idfield: 'genomic_info_id'
  update_study_participant_id:
    refnode: 'participant'
    refpartid: 'participant_id'
    refstudypartid: 'study_participant_id'
    nodes:
      - 'diagnosis'
      - 'sample'
    idfield: 'participant.study_participant_id'