# This is a list of dictionry.  Key is the node, value is the full file path
submissionfiles:
  - diagnosis: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Netrias\Netrias_CCDI_Templates\Netrias_CCDI_Templates\phs003519_CCDI_Study_Manifest 1\GC_Data_Loading_Template_diagnosis_v6.0.4.tsv'
  - file: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Netrias\Netrias_CCDI_Templates\Netrias_CCDI_Templates\phs003519_CCDI_Study_Manifest 1\GC_Data_Loading_Template_file_v6.0.4.tsv'
  #- genomic_info: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Netrias\Netrias_CCDI_Templates\Netrias_CCDI_Templates\phs000720_CCDI_Study_Manifest 1\GC_Data_Loading_Template_genomic_info_v6.0.4.tsv'
  - participant: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Netrias\Netrias_CCDI_Templates\Netrias_CCDI_Templates\phs003519_CCDI_Study_Manifest 1\GC_Data_Loading_Template_participant_v6.0.4.tsv'
  - sample: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Netrias\Netrias_CCDI_Templates\Netrias_CCDI_Templates\phs003519_CCDI_Study_Manifest 1\GC_Data_Loading_Template_sample_v6.0.4.tsv'
  - study: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Netrias\Netrias_CCDI_Templates\Netrias_CCDI_Templates\phs003519_CCDI_Study_Manifest 1\GC_Data_Loading_Template_study_v6.0.4.tsv'
  - program: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Netrias\Netrias_CCDI_Templates\Netrias_CCDI_Templates\phs003519_CCDI_Study_Manifest 1\GC_Data_Loading_Template_program_v6.0.4.tsv'
  #- multiplexmicroscopy: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Netrias\Netrias_CCDI_Templates\Netrias_CCDI_Templates\phs000720_CCDI_Study_Manifest 1\GC_Data_Loading_Template_MultiplexMicroscopy_v6.0.4.tsv'
  #- image: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\Netrias\Netrias_CCDI_Templates\Netrias_CCDI_Templates\phs000720_CCDI_Study_Manifest 1\GC_Data_Loading_Template_image_v6.0.4.tsv'
separator: 'tab'  #Can be tab or comma
outputdir: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\TDP Fixes\Netrias\phs003519\'
 #Available fixes
    # fileid - populates the file_id column of the file node
    # addphs: Adds the study phs number to the listed sheets in the study.phs_accession column
    # study_participant_id: Creates the study_participant_id and populates the column
    # diagnosis_id
    # study_diagnosis_id:  Creates a study_diagnosis_id 
    # genomic_info_id: Creates a genonmic_info_id
    # update_study_participant_id: Use if there is just a patient id in the study_participant_id columns
fixes:
  phs: 'phs003519'
  fileid: 
    file: 'file_id'
  addphs:
    nodes:
      - 'participant'
      - 'file'
    participant: 'study.phs_accession'
    study: 'phs_accession'
  study_participant_id:
    participant: 'study_participant_id'
  diagnosis_id:
    idfield: 'diagnosis_id'
    diagnosis: 'primary_diagnosis'
    site: 'primary_site'
  study_diagnosis_id:
    idfield: 'study_diagnosis_id'
    diagnosis: 'diagnosis_id'
    participant: 'participant.study_participant_id'
  update_study_participant_id:
    refnode: 'participant'
    refpartid: 'participant_id'
    refstudypartid: 'study_participant_id'
    nodes:
      - 'diagnosis'
      - 'sample'
      - 'file'
    idfield: 'participant.study_participant_id'
  #add_uuid:
  #  nodes:
  #    - 'genomic_info': 'genomic_info_id'