RegEx:
  date_regex:
    test: '(0?[1-9]|1[0-2])[-\\/.](0?[1-9]|[12][0-9]|3[01])[-\\/.](19[0-9]{2}|2[0-9]{3}|[0-9]{2})',
             '(19[0-9]{2}|2[0-9]{3})[-\\/.](0?[1-9]|1[0-2])[-\\/.](0?[1-9]|[12][0-9]|3[01])',
             '(0?[1-9]|[12][0-9]|3[01])[\\/](19[0-9]{2}|2[0-9]{3})',
             '(0?[1-9]|[12][0-9])[\\/]([0-9]{2})',
             '(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])[0-9]{2}',
             '(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])19[0-9]{2}',
             '(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])2[0-9]{3}',
             '19[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])',
             '2[0-9]{3}(0[1-9]|1[0-2])(0[1-9]|[12][0-9]|3[01])'
    error: "Found potential date"
  socsec_regex:
      test: '[0-9]{3}[-][0-9]{2}[-][0-9]{4}'
      error: "Found potential Social Secuirty number"
  phone_regex:
    test: '[(]?[0-9]{3}[-)\ ][0-9]{3}[-][0-9]{4}'
    error: "Found potential phone number"
  zip_regex:
    test: '(^[0-9]{5}$)|(^[0-9]{9}$)|(^[0-9]{5}-[0-9]{4}$)'
    error: "Found potential ZIP code"