# This is a list of dictionry.  Key is the node, value is the full file path
submissionfiles:
  - diagnosis: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\SageBio\output_set_2\diagnosis.csv'
  - file: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\SageBio\output_set_2\file.csv'
  - genomic_info: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\SageBio\output_set_2\genomic_info.csv'
  - participant: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\SageBio\output_set_2\participant.csv'
  - sample: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\SageBio\output_set_2\sample.csv'
  - study: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\SageBio\output_set_2\study.csv'
  - program: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\SageBio\output_set_2\program.csv'
separator: 'comma'  #Can be tab or comma
outputdir: 'C:\Users\pihltd\OneDrive - National Institutes of Health\FNLCR Projects\ARPA-H\CCDI-CDS Challenge\TDP Fixes\SageBio\output_set_2\'
 #Available fixes
    # fileid - populates the file_id column of the file node
    # addphs: Adds the study phs number to the listed sheets in the study.phs_accession column
    # study_participant_id: Creates the study_participant_id and populates the column
    # diagnosis_id
    # study_diagnosis_id:  Creates a study_diagnosis_id 
    # genomic_info_id: Creates a genonmic_info_id
    # update_study_participant_id: Use if there is just a patient id in the study_participant_id columns
fixes:
  phs: 'phs000720'
  fileid: 
    file: 'file_id'
  addphs:
    nodes:
      - 'participant'
      - 'file'
    participant: 'study.phs_accession'
    study: 'phs_accession'
  study_participant_id:
    participant: 'study_participant_id'
  diagnosis_id:
    idfield: 'diagnosis_id'
    diagnosis: 'primary_diagnosis'
    site: 'primary_site'
  study_diagnosis_id:
    idfield: 'study_diagnosis_id'
    diagnosis: 'diagnosis_id'
    participant: 'participant.study_participant_id'
  update_study_participant_id:
    refnode: 'participant'
    refpartid: 'participant_id'
    refstudypartid: 'study_participant_id'
    nodes:
      - 'diagnosis'
      - 'sample'
      - 'file'
    idfield: 'participant.study_participant_id'
  add_uuid:
    nodes:
      - 'genomic_info': 'genomic_info_id'
